force-app/main/default/objects/Flow_Deletion_Setting__c/Flow_Deletion_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Controls whether users can delete flow versions or not.</description>
    <label>Flow Deletion Setting</label>
</CustomObject>

force-app/main/default/objects/Flow_Deletion_Setting__c/fields/Allow_Deletion__c.field-meta.xml
<CustomField>
    <fullName>Allow_Deletion__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When false/unchecked users will be blocked from deleting flows by a trigger throwing an error.</description>
    <inlineHelpText>When false/unchecked users will be blocked from deleting flows by a trigger throwing an error.</inlineHelpText>
    <label>Allow Deletion?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/FlowDeletionSettingSchedulerTest.cls
@isTest
private class FlowDeletionSettingSchedulerTest {
    @isTest
    static void testSchedulerUpdatesAllowDeletion() {
        // Create org default custom setting with Allow_Deletion__c = true
        Flow_Deletion_Setting__c setting = new Flow_Deletion_Setting__c(
            SetupOwnerId = UserInfo.getOrganizationId(),
            Allow_Deletion__c = true
        );
        insert setting;

        // Run the scheduler
        Test.startTest();
        FlowDeletionSettingScheduler scheduler = new FlowDeletionSettingScheduler();
        scheduler.execute(null);
        Test.stopTest();

        // Verify the setting was updated
        Flow_Deletion_Setting__c updated = Flow_Deletion_Setting__c.getOrgDefaults();
        System.assertEquals(false, updated.Allow_Deletion__c, 'Allow_Deletion__c should be set to false');
    }
}