force-app/main/default/objects/Flow_Deletion_Setting__c/Flow_Deletion_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Controls whether users can delete flow versions or not.</description>
    <label>Flow Deletion Setting</label>
</CustomObject>

force-app/main/default/objects/Flow_Deletion_Setting__c/fields/Allow_Deletion__c.field-meta.xml
<CustomField>
    <fullName>Allow_Deletion__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When false/unchecked users will be blocked from deleting flows by a trigger throwing an error.</description>
    <inlineHelpText>When false/unchecked users will be blocked from deleting flows by a trigger throwing an error.</inlineHelpText>
    <label>Allow Deletion?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/FlowDeletionSettingScheduler.cls
public with sharing class FlowDeletionSettingScheduler implements Schedulable{
    public void execute(SchedulableContext sc){
        Flow_Deletion_Setting__c flowDeletionSetting = Flow_Deletion_Setting__c.getOrgDefaults();

        if(flowDeletionSetting.Allow_Deletion__c){
            flowDeletionSetting.Allow_Deletion__c = false;
            update flowDeletionSetting;
            System.debug('Flow deletion setting automatically reverted to false at: ' + System.now());
           }
    }
    /*
    // Schedule to run every hour at minute 0 - run in anonymous apex
        String cronExp = '0 0 * * * ?';
        String jobName = 'Flow Deletion Setting Reset';
        System.schedule(jobName, cronExp, new FlowDeletionSettingScheduler());
    */
}