force-app/main/default/objects/Flow_Deletion_Setting__mdt/Flow_Deletion_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Object that holds a single record that can be used to toggle on/off allowing the deletion of flow versions.</description>
    <label>Flow Deletion Setting</label>
    <pluralLabel>Flow Deletions</pluralLabel>
</CustomObject>

force-app/main/default/objects/Flow_Deletion_Setting__mdt/fields/Allow_Deletion__c.field-meta.xml
<CustomField>
    <fullName>Allow_Deletion__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Should users be able to delete flow versions?</description>
    <inlineHelpText>Should users be able to delete flow versions?</inlineHelpText>
    <label>Allow Deletion?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/FlowRecordVersionTriggerHandler.cls
public with sharing class FlowRecordVersionTriggerHandler {

    public static void handleDelete(List<FlowRecordVersion> triggerDotOld) {
        Flow_Deletion_Setting__mdt flowDeletionSetting = Flow_Deletion_Setting__mdt.getInstance('Flow_Deletion_Setting');
        if(flowDeletionSetting.Allow_Deletion__c == false){
            for (FlowRecordVersion frv : triggerDotOld) {
            frv.addError(Label.Flow_Deletion_Error);    
        }
        }
        
    }
}